/* Auto-extracted from the original site. */

export const PROPS = Object.assign({}, {
   aureus:{dev:"Lodha",name:"Lodha Aureus",loc:"Sewri",imgs:["aureus_entrance","aureus_living"],
     desc:"Art Deco residences on Sewri's waterfront, with wide horizontal living rooms, grand decks and views across the bay and the Grand Central Garden.",
     specs:[["3 BHK \u00b7 1,148 sq ft","From \u20b94.6 Cr"],["3 BHK Large \u00b7 1,442 sq ft","\u20b96.3 Cr"],["4 BHK \u00b7 1,731 sq ft","\u20b97.8 Cr"],["4 BHK Large \u00b7 2,326 sq ft","\u20b910.7 Cr"]]},
   sobha:{dev:"Sobha",name:"Sobha Inizio",loc:"Parel",imgs:["sobha_dusk","sobha_ext","sobha_lobby"],
     desc:"A single landmark tower with a double-height grand lobby and a Club in the Sky, its homes framing Waterscape and Atal Setu views.",
     specs:[["2 BHK \u00b7 847 sq ft","From \u20b94.55 Cr"],["3 BHK Luxe \u00b7 1,021 sq ft","\u20b95.48 Cr"],["3 BHK Grand \u00b7 1,225 sq ft","\u20b96.58 Cr"]]},
   icc:{dev:"Bombay Realty",name:"Three ICC",loc:"Island City Center, Dadar",imgs:["icc"],
     desc:"Ultra-spacious Deck Residences on freehold land in the heart of Dadar, with 10 ft floor-to-floor heights and a 30,000 sq ft clubhouse.",
     specs:[["4 Bed \u00b7 2,143 sq ft","From \u20b95.75 Cr"],["4.5 Bed \u00b7 2,582 sq ft","On request"],["5 Bed \u00b7 2,994 sq ft","On request"]]},
   divino:{dev:"Lodha",name:"Lodha Divino",loc:"Sion",imgs:["divino_greens","divino_pool"],
     desc:"A new tower of 3.5 and 4.5 bed homes beside the greens of Five Gardens, with a landscaped clubhouse, pools and a retail promenade.",
     specs:[["3.5 BHK \u00b7 approx 1,400 sq ft","Now launching"],["4.5 BHK \u00b7 approx 1,700 sq ft","Now launching"]]},
   raheja:{dev:"K Raheja Corp",name:"Raheja Amaltis",loc:"Sion",imgs:["raheja_elevation","raheja_entrance","raheja_rooftop","raheja_lobby"],
     desc:"A launching landmark in the heart of Sion, next to the BKC connector. Exquisite 3, 3.5 and 4 bed homes with decks and 11 ft 2 in floor-to-floor heights, crowned by a rooftop with an infinity pool, sky bar and sky dining pavilion.",
     specs:[["3 Bed with deck","From \u20b95.07 Cr"],["3.5 Bed with deck","On request"],["4 Bed with deck","On request"]]},
   godrejh:{dev:"Godrej",name:"Godrej Horizon",loc:"Wadala West",imgs:["godrej_horizon"],
     desc:"A curated address in the current portfolio, with generously proportioned interiors and a refined, contemporary material palette. Configurations and pricing shared privately, on request.",
     specs:[["Starting price","From \u20b93.75 Cr"]]},
   kalpataru:{dev:"Kalpataru",name:"Kalpataru One",loc:"Worli",imgs:["kalpataru_ext","kalpataru_crown","kalpataru_living"],
     desc:"A landmark sea-facing tower rising over the bay, with a crowning sky deck, illuminated residences and homes that frame the water and the city skyline.",
     specs:[["Price","\u20b928.75 Cr"]]}
  }, {kalpataru_avana:{dev:"Kalpataru",name:"Kalpataru Avana",loc:"Parel",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770647815/gallery/a139a818-c26e-46be-a1a1-fba4be90c2fc.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770647820/gallery/065ee4df-4475-4f58-ae1a-7d62360a1de7.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770647823/gallery/f7c95031-f3bb-4127-8b39-7b17e5f33ad1.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770647827/gallery/0c9228d7-b812-42a0-a895-a67864dce5a4.webp"],desc:"A landmark residence in Parel by Kalpataru. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹12.55 Cr"],["Possession","Ready to move"]]},lt_gateway:{dev:"L&T",name:"L&T Gateway",loc:"Parel",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766579770/gallery/31a9db50-7e7e-4c96-b976-b30568530dbb.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766579783/gallery/fc0b9d02-8a2f-4656-bc93-650505b2c419.png","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766579786/gallery/f27c0ba4-7573-4454-bc78-def02536da6a.png","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766579794/gallery/d7be0353-5b0b-4a2a-a47a-7f00beb702fd.png"],desc:"A landmark residence in Parel by L&T. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹10.70 Cr"],["Possession","Under construction"]]},sattva_sumera:{dev:"Sattva",name:"Sattva Sumera",loc:"Parel",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769196109/gallery/32b98812-2b6c-4ec2-8ed7-f3c09b576557.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769196110/gallery/c651f19d-c0f0-4891-9fce-6a1d99c3e414.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769196114/gallery/5ea59d8c-ef38-4ac1-890b-258b6a13fbfd.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769196117/gallery/c48986a1-9e34-4c6c-9a79-c80de4248a18.webp"],desc:"A landmark residence in Parel by Sattva. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹3.37 Cr"],["Possession","Under construction"]]},lodha_vero:{dev:"Lodha",name:"Lodha Vero",loc:"Sion",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767037095/gallery/75218d94-3922-4ee9-baee-59fb53cb668c.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767037216/gallery/ec1494c0-3bb9-4d97-bc38-82de05a88029.jpg","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767037218/gallery/9ecb3f2e-e011-4a93-942e-f6f287d5e0b1.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767037221/gallery/71b95ec9-d665-42f5-8cad-e40e0cdcc294.webp"],desc:"A landmark residence in Sion by Lodha. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹10.50 Cr"],["Possession","Under construction"]]},lodha_the_park:{dev:"Lodha",name:"Lodha The Park",loc:"Lower Parel",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768930924/gallery/ccc60c35-75a8-430b-8171-788b0b517e97.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768930927/gallery/d73df154-e6cf-40d5-b25f-00253509d1a1.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768930935/gallery/f509142b-33a8-4876-8304-d2401282e336.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768930940/gallery/655f2ea3-2d29-402a-8fad-6ae708125aea.webp"],desc:"A landmark residence in Lower Parel by Lodha. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹6.60 Cr"],["Possession","Ready to move"]]},lodha_world_tower:{dev:"Lodha",name:"Lodha World Tower",loc:"Lower Parel",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769020521/gallery/602e2fd9-159f-4ed1-a62f-21b89a81c409.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769020526/gallery/1e6b4ac7-d3f0-4610-943d-e2519ed243ff.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769020529/gallery/1693322f-0baf-4522-b6d3-d2a9bad6b62c.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769020531/gallery/da30d60a-7d68-4f9e-837f-d7c6c2c08023.webp"],desc:"A landmark residence in Lower Parel by Lodha. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹10.80 Cr"],["Possession","Ready to move"]]},raheja_imperia:{dev:"K Raheja Corp",name:"Raheja Imperia",loc:"Lower Parel",imgs:["raheja_rivere_img","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768069595/gallery/11d3e2a6-27af-4f98-b7e1-6ca138bb3bbf.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768069597/gallery/d0eb871e-0793-45b8-8c15-15e51a472365.webp"],desc:"A landmark residence in Lower Parel by K Raheja Corp. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹8.99 Cr"],["Possession","Under construction"]]},raheja_rivere:{dev:"K Raheja Corp",name:"Raheja Rivere",loc:"Lower Parel",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768069595/gallery/11d3e2a6-27af-4f98-b7e1-6ca138bb3bbf.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768069597/gallery/d0eb871e-0793-45b8-8c15-15e51a472365.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768069600/gallery/4e0a3fe0-8e3c-4179-9142-36a344cc1fa9.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768069607/gallery/5cb7d22f-8527-4a7e-a5cc-6a4511931b84.webp"],desc:"A landmark residence in Lower Parel by K Raheja Corp. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹8.99 Cr"],["Possession","Under construction"]]},runwal_raaya:{dev:"Runwal",name:"Runwal Raaya",loc:"Worli",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766659993/gallery/ba12dcf2-b20b-454c-9fad-84b63eb79b8d.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766659995/gallery/2fc4e651-8ac1-4982-a71f-6aa82830244b.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766659998/gallery/e0527754-3e93-4a9c-aa8a-d0bc88549684.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766660002/gallery/25828860-fda7-4ee6-b5b3-ae4aab5aa288.webp"],desc:"A landmark residence in Worli by Runwal. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹11.29 Cr"],["Possession","Under construction"]]},lodha_bellevue:{dev:"Lodha",name:"Lodha Bellevue",loc:"Mahalaxmi",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766488230/gallery/362bb62c-e770-484c-abec-20250b50bfc7.jpg","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766488234/gallery/5df00f60-3522-450f-a227-7385846652c6.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766488256/gallery/1d281905-bf34-4f5d-b0da-b80544f0dd74.jpg","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766488290/gallery/3725b1f4-5751-41b5-9aae-e87e75666244.jpg"],desc:"A landmark residence in Mahalaxmi by Lodha. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹4.80 Cr"],["Possession","Under construction"]]},piramal_mahalaxmi:{dev:"Piramal",name:"Piramal Mahalaxmi",loc:"Mahalaxmi",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766480679/gallery/acb98426-3451-4862-b130-6b4ac3a96826.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766480684/gallery/a511f333-1ab9-430a-a4e6-e06b6a1eccef.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766480698/gallery/24f30bc6-fdfa-4244-b3f8-e6a8fb35e021.png","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766480705/gallery/7d022637-9c03-4eeb-847f-7902f4146d50.png"],desc:"A landmark residence in Mahalaxmi by Piramal. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹4.07 Cr"],["Possession","Ready to move"]]},godrej_avenue_eleven:{dev:"Godrej",name:"Godrej Avenue Eleven",loc:"Mahalaxmi",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766438415/gallery/d3c05c32-e983-4f1f-8d61-3490f2c4f895.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766438424/gallery/4297c56b-f3ff-48d4-a895-7262bc6c42b4.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766438489/gallery/6adb92e3-da41-4d80-8e46-dd793bc14c07.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766438497/gallery/aff9c40b-8638-41db-8ffc-80c0f0e4273e.webp"],desc:"A landmark residence in Mahalaxmi by Godrej. Configurations and floor plans shared on request.",specs:[["Price","₹11.5 Cr"],["Possession","Under construction"]]},raheja_modern_vivarea:{dev:"K Raheja Corp",name:"Raheja Modern Vivarea",loc:"Mahalaxmi",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1771514885/gallery/48e3dfc3-a777-4cdd-b855-f4a17bad523c.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767727010/gallery/ac77edbe-822b-4385-8017-b57d7dc6db4f.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767727018/gallery/4d65752a-6124-4894-b2f1-c0511d0a0f25.jpg","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767727020/gallery/570a7ad3-1266-45da-98e7-a2f79584fac4.webp"],desc:"A landmark residence in Mahalaxmi by K Raheja Corp. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹12.52 Cr"],["Possession","Under construction"]]},shapoorji_minerva:{dev:"Shapoorji Pallonji",name:"Shapoorji Minerva",loc:"Mahalaxmi",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767730739/gallery/99fcb223-ff4b-42c4-9591-e66a5ccdaa4d.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767730741/gallery/b9087b22-57d4-4097-b2df-5c1872d8e752.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767730745/gallery/b13ed30d-8030-4c71-89ea-7f1413688ebc.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767730749/gallery/74944fa0-371d-40ea-8d3a-e58321ea31ba.webp"],desc:"A landmark residence in Mahalaxmi by Shapoorji Pallonji. Configurations and floor plans shared on request.",specs:[["Price","₹10 Cr"],["Possession","Ready to move"]]},rustomjee_crown:{dev:"Rustomjee",name:"Rustomjee Crown",loc:"Prabhadevi",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767121586/gallery/cc23d769-c4ec-4deb-8e2c-36dc0cde0c64.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767121588/gallery/544051b5-6021-4ed9-8b92-6e25f15511ba.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767121591/gallery/b4922561-c7f0-4ead-acfc-0580ef131df1.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767121594/gallery/18236bc2-6ab0-4d6c-adb4-2d354da05f2e.webp"],desc:"A landmark residence in Prabhadevi by Rustomjee. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹9.75 Cr"],["Possession","Ready to move"]]},rustomjee_180_bay_view:{dev:"Rustomjee",name:"Rustomjee 180 Bay View",loc:"Matunga",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770405979/gallery/95f53267-ba4f-44c8-916b-a53c92e38ad7.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770405982/gallery/e5704678-4dfe-4eb3-8f4e-aec119a695e8.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770405985/gallery/ada3b045-1637-4e4c-9dca-9317fb5e4e6e.webp","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770405989/gallery/698020d8-093c-459f-ad30-e8697b3ee37e.webp"],desc:"A landmark residence in Matunga by Rustomjee. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹4.12 Cr"],["Possession","Under construction"]]},lt_island_cove:{dev:"L&T",name:"L&T Island Cove",loc:"Mahim",imgs:["https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766663940/gallery/b7c98561-d06f-42b3-a47e-acc5b067516b.png","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766663959/gallery/21a1b28c-d506-496b-a778-312dc44c4e3f.png","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766663971/gallery/272984f8-baef-4183-ae48-448a7e1d1e34.png","https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766663977/gallery/d82f17d1-e111-4853-a4fc-91612b479838.png"],desc:"A landmark residence in Mahim by L&T. Configurations and floor plans shared on request.",specs:[["Starting price","From ₹3.25 Cr"],["Possession","Under construction"]]}});

export const HOME_CARDS = [
 {
  "np": false,
  "prop": "aureus",
  "img": "aureus_entrance",
  "loc": "Sewri",
  "status": null,
  "bud": "b1,b2,b3",
  "phUrl": null,
  "phClass": "bg-aureus_entrance",
  "dev": "Lodha",
  "badge": "From ₹4.6 Cr",
  "statusLabel": null,
  "npLoc": null,
  "price2": null,
  "name": "Lodha Aureus",
  "locText": "Sewri",
  "meta": "Art Deco 3 & 4 bed residences, panoramic waterfront and Central Garden views.",
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "sobha",
  "img": "sobha_dusk",
  "loc": "Parel",
  "status": null,
  "bud": "b1,b2",
  "phUrl": null,
  "phClass": "bg-sobha_dusk",
  "dev": "Sobha",
  "badge": "From ₹4.55 Cr",
  "statusLabel": null,
  "npLoc": null,
  "price2": null,
  "name": "Sobha Inizio",
  "locText": "Parel",
  "meta": "A single landmark tower with a Club in the Sky, 2 & 3 bed homes with Waterscape views.",
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "icc",
  "img": "icc",
  "loc": "Dadar",
  "status": null,
  "bud": "b2,b3",
  "phUrl": null,
  "phClass": "bg-icc",
  "dev": "Bombay Realty",
  "badge": "From ₹5.75 Cr",
  "statusLabel": null,
  "npLoc": null,
  "price2": null,
  "name": "Three ICC",
  "locText": "Dadar",
  "meta": "Ultra-spacious 4 to 5 bed Deck Residences on freehold land, 10 ft floor-to-floor heights.",
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "divino",
  "img": "divino_greens",
  "loc": "Other",
  "status": null,
  "bud": "any",
  "phUrl": null,
  "phClass": "bg-divino_greens",
  "dev": "Lodha",
  "badge": "Now launching",
  "statusLabel": null,
  "npLoc": null,
  "price2": null,
  "name": "Lodha Divino",
  "locText": "Sion",
  "meta": "A new tower of 3.5 & 4.5 bed homes beside the greens of Five Gardens.",
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "raheja",
  "img": "raheja_elevation",
  "loc": "Sion",
  "status": null,
  "bud": "b2,b3",
  "phUrl": null,
  "phClass": "bg-raheja_elevation",
  "dev": "K Raheja Corp",
  "badge": "From ₹5.07 Cr",
  "statusLabel": null,
  "npLoc": null,
  "price2": null,
  "name": "Raheja Amaltis",
  "locText": "Sion",
  "meta": "Exquisite 3, 3.5 & 4 bed homes with decks, next to the BKC connector.",
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "godrejh",
  "img": "godrej_horizon",
  "loc": null,
  "status": null,
  "bud": null,
  "phUrl": null,
  "phClass": "bg-godrej_horizon",
  "dev": "Godrej",
  "badge": "From ₹3.75 Cr",
  "statusLabel": null,
  "npLoc": null,
  "price2": null,
  "name": "Godrej Horizon",
  "locText": "Wadala West",
  "meta": "A curated address in the current portfolio, with refined, contemporary interiors.",
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "kalpataru",
  "img": "kalpataru_ext",
  "loc": null,
  "status": null,
  "bud": null,
  "phUrl": null,
  "phClass": "bg-kalpataru_ext",
  "dev": "Kalpataru",
  "badge": "₹28.75 Cr",
  "statusLabel": null,
  "npLoc": null,
  "price2": null,
  "name": "Kalpataru One",
  "locText": "Worli",
  "meta": "A landmark sea-facing tower with a crowning sky deck and expansive residences over the bay.",
  "vw": "View details →"
 }
];

export const PROP_CARDS = [
 {
  "np": false,
  "prop": "sobha",
  "img": "sobha_dusk",
  "loc": "Parel",
  "status": "Under construction",
  "bud": "b1,b2",
  "phUrl": null,
  "phClass": "bg-sobha_dusk",
  "dev": "Sobha",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹4.55 Cr",
  "name": "Sobha Inizio",
  "locText": "Parel",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "kalpataru_avana",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770647815/gallery/a139a818-c26e-46be-a1a1-fba4be90c2fc.webp",
  "loc": "Parel",
  "status": "Ready to move",
  "bud": "b3,b4",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770647815/gallery/a139a818-c26e-46be-a1a1-fba4be90c2fc.webp",
  "phClass": null,
  "dev": "Kalpataru",
  "badge": null,
  "statusLabel": "Ready to move",
  "npLoc": null,
  "price2": "From ₹12.55 Cr",
  "name": "Kalpataru Avana",
  "locText": "Parel",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": true,
  "prop": null,
  "img": null,
  "loc": "Parel",
  "status": "Ready to move",
  "bud": "",
  "phUrl": null,
  "phClass": null,
  "dev": null,
  "badge": null,
  "statusLabel": "Ready to move",
  "npLoc": "Parel",
  "price2": null,
  "name": "L&T Crescent Bay",
  "locText": "Parel",
  "meta": null,
  "vw": "Enquire →"
 },
 {
  "np": false,
  "prop": "lt_gateway",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766579770/gallery/31a9db50-7e7e-4c96-b976-b30568530dbb.webp",
  "loc": "Parel",
  "status": "Under construction",
  "bud": "b3,b4",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766579770/gallery/31a9db50-7e7e-4c96-b976-b30568530dbb.webp",
  "phClass": null,
  "dev": "L&T",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹10.70 Cr",
  "name": "L&T Gateway",
  "locText": "Parel",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": true,
  "prop": null,
  "img": null,
  "loc": "Parel",
  "status": "Under construction",
  "bud": "",
  "phUrl": null,
  "phClass": null,
  "dev": null,
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": "Parel",
  "price2": null,
  "name": "Rustomjee Vista Bay",
  "locText": "Parel",
  "meta": null,
  "vw": "Enquire →"
 },
 {
  "np": false,
  "prop": "sattva_sumera",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769196109/gallery/32b98812-2b6c-4ec2-8ed7-f3c09b576557.webp",
  "loc": "Parel",
  "status": "Under construction",
  "bud": "b1,b2",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769196109/gallery/32b98812-2b6c-4ec2-8ed7-f3c09b576557.webp",
  "phClass": null,
  "dev": "Sattva",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹3.37 Cr",
  "name": "Sattva Sumera",
  "locText": "Parel",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "icc",
  "img": "icc",
  "loc": "Dadar",
  "status": "Under construction",
  "bud": "b2,b3",
  "phUrl": null,
  "phClass": "bg-icc",
  "dev": "Bombay Realty",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹5.75 Cr",
  "name": "Three ICC",
  "locText": "Dadar",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": true,
  "prop": null,
  "img": null,
  "loc": "Dadar",
  "status": "Ready to move",
  "bud": "",
  "phUrl": null,
  "phClass": null,
  "dev": null,
  "badge": null,
  "statusLabel": "Ready to move",
  "npLoc": "Dadar",
  "price2": null,
  "name": "Bombay Dyeing Springs",
  "locText": "Dadar",
  "meta": null,
  "vw": "Enquire →"
 },
 {
  "np": true,
  "prop": null,
  "img": null,
  "loc": "Dadar",
  "status": "Ready to move",
  "bud": "",
  "phUrl": null,
  "phClass": null,
  "dev": null,
  "badge": null,
  "statusLabel": "Ready to move",
  "npLoc": "Dadar",
  "price2": null,
  "name": "Bombay Dyeing ICC Two",
  "locText": "Dadar",
  "meta": null,
  "vw": "Enquire →"
 },
 {
  "np": false,
  "prop": "godrejh",
  "img": "godrej_horizon",
  "loc": "Wadala West",
  "status": "Under construction",
  "bud": "b2,b3",
  "phUrl": null,
  "phClass": "bg-godrej_horizon",
  "dev": "Godrej",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹3.75 Cr",
  "name": "Godrej Horizon",
  "locText": "Wadala West",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "aureus",
  "img": "aureus_entrance",
  "loc": "Sewri",
  "status": "Under construction",
  "bud": "b1,b2,b3",
  "phUrl": null,
  "phClass": "bg-aureus_entrance",
  "dev": "Lodha",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹4.6 Cr",
  "name": "Lodha Aureus",
  "locText": "Sewri",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "divino",
  "img": "divino_greens",
  "loc": "Sion",
  "status": "New launch",
  "bud": "",
  "phUrl": null,
  "phClass": "bg-divino_greens",
  "dev": "Lodha",
  "badge": null,
  "statusLabel": "New launch",
  "npLoc": null,
  "price2": "Now launching",
  "name": "Lodha Divino",
  "locText": "Sion",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "raheja",
  "img": "raheja_elevation",
  "loc": "Sion",
  "status": "New launch",
  "bud": "b2,b3",
  "phUrl": null,
  "phClass": "bg-raheja_elevation",
  "dev": "K Raheja Corp",
  "badge": null,
  "statusLabel": "New launch",
  "npLoc": null,
  "price2": "From ₹5.07 Cr",
  "name": "Raheja Amaltis",
  "locText": "Sion",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "lodha_vero",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767037095/gallery/75218d94-3922-4ee9-baee-59fb53cb668c.webp",
  "loc": "Sion",
  "status": "Under construction",
  "bud": "b3,b4",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767037095/gallery/75218d94-3922-4ee9-baee-59fb53cb668c.webp",
  "phClass": null,
  "dev": "Lodha",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹10.50 Cr",
  "name": "Lodha Vero",
  "locText": "Sion",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "lodha_the_park",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768930924/gallery/ccc60c35-75a8-430b-8171-788b0b517e97.webp",
  "loc": "Lower Parel",
  "status": "Ready to move",
  "bud": "b2,b3",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768930924/gallery/ccc60c35-75a8-430b-8171-788b0b517e97.webp",
  "phClass": null,
  "dev": "Lodha",
  "badge": null,
  "statusLabel": "Ready to move",
  "npLoc": null,
  "price2": "From ₹6.60 Cr",
  "name": "Lodha The Park",
  "locText": "Lower Parel",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "lodha_world_tower",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769020521/gallery/602e2fd9-159f-4ed1-a62f-21b89a81c409.webp",
  "loc": "Lower Parel",
  "status": "Ready to move",
  "bud": "b3,b4",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1769020521/gallery/602e2fd9-159f-4ed1-a62f-21b89a81c409.webp",
  "phClass": null,
  "dev": "Lodha",
  "badge": null,
  "statusLabel": "Ready to move",
  "npLoc": null,
  "price2": "From ₹10.80 Cr",
  "name": "Lodha World Tower",
  "locText": "Lower Parel",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "raheja_imperia",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768069595/gallery/11d3e2a6-27af-4f98-b7e1-6ca138bb3bbf.webp",
  "loc": "Lower Parel",
  "status": "Under construction",
  "bud": "b2,b3",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1768069595/gallery/11d3e2a6-27af-4f98-b7e1-6ca138bb3bbf.webp",
  "phClass": null,
  "dev": "K Raheja Corp",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹8.99 Cr",
  "name": "Raheja Imperia",
  "locText": "Lower Parel",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "raheja_rivere",
  "img": "raheja_rivere_img",
  "loc": "Lower Parel",
  "status": "Under construction",
  "bud": "b2,b3",
  "phUrl": null,
  "phClass": "bg-raheja_rivere_img",
  "dev": "K Raheja Corp",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹8.99 Cr",
  "name": "Raheja Rivere",
  "locText": "Lower Parel",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "kalpataru",
  "img": "kalpataru_ext",
  "loc": "Worli",
  "status": "Under construction",
  "bud": "b5,b6",
  "phUrl": null,
  "phClass": "bg-kalpataru_ext",
  "dev": "Kalpataru",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "₹28.75 Cr",
  "name": "Kalpataru One",
  "locText": "Worli",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": true,
  "prop": null,
  "img": null,
  "loc": "Worli",
  "status": "",
  "bud": "",
  "phUrl": null,
  "phClass": null,
  "dev": null,
  "badge": null,
  "statusLabel": null,
  "npLoc": "Worli",
  "price2": null,
  "name": "Indiabulls Blu",
  "locText": "Worli",
  "meta": null,
  "vw": "Enquire →"
 },
 {
  "np": true,
  "prop": null,
  "img": null,
  "loc": "Worli",
  "status": "",
  "bud": "",
  "phUrl": null,
  "phClass": null,
  "dev": null,
  "badge": null,
  "statusLabel": null,
  "npLoc": "Worli",
  "price2": null,
  "name": "Embassy Citadel",
  "locText": "Worli",
  "meta": null,
  "vw": "Enquire →"
 },
 {
  "np": false,
  "prop": "runwal_raaya",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766659993/gallery/ba12dcf2-b20b-454c-9fad-84b63eb79b8d.webp",
  "loc": "Worli",
  "status": "Under construction",
  "bud": "b3,b4",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766659993/gallery/ba12dcf2-b20b-454c-9fad-84b63eb79b8d.webp",
  "phClass": null,
  "dev": "Runwal",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹11.29 Cr",
  "name": "Runwal Raaya",
  "locText": "Worli",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": true,
  "prop": null,
  "img": null,
  "loc": "Worli",
  "status": "",
  "bud": "",
  "phUrl": null,
  "phClass": null,
  "dev": null,
  "badge": null,
  "statusLabel": null,
  "npLoc": "Worli",
  "price2": null,
  "name": "Palais Royale",
  "locText": "Worli",
  "meta": null,
  "vw": "Enquire →"
 },
 {
  "np": false,
  "prop": "lodha_bellevue",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766488230/gallery/362bb62c-e770-484c-abec-20250b50bfc7.jpg",
  "loc": "Mahalaxmi",
  "status": "Under construction",
  "bud": "b1,b2",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766488230/gallery/362bb62c-e770-484c-abec-20250b50bfc7.jpg",
  "phClass": null,
  "dev": "Lodha",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹4.80 Cr",
  "name": "Lodha Bellevue",
  "locText": "Mahalaxmi",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "piramal_mahalaxmi",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766480679/gallery/acb98426-3451-4862-b130-6b4ac3a96826.webp",
  "loc": "Mahalaxmi",
  "status": "Ready to move",
  "bud": "b1,b2",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766480679/gallery/acb98426-3451-4862-b130-6b4ac3a96826.webp",
  "phClass": null,
  "dev": "Piramal",
  "badge": null,
  "statusLabel": "Ready to move",
  "npLoc": null,
  "price2": "From ₹4.07 Cr",
  "name": "Piramal Mahalaxmi",
  "locText": "Mahalaxmi",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "godrej_avenue_eleven",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766438415/gallery/d3c05c32-e983-4f1f-8d61-3490f2c4f895.webp",
  "loc": "Mahalaxmi",
  "status": "Under construction",
  "bud": "b1,b2",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766438415/gallery/d3c05c32-e983-4f1f-8d61-3490f2c4f895.webp",
  "phClass": null,
  "dev": "Godrej",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "₹11.5 Cr",
  "name": "Godrej Avenue Eleven",
  "locText": "Mahalaxmi",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "raheja_modern_vivarea",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1771514885/gallery/48e3dfc3-a777-4cdd-b855-f4a17bad523c.webp",
  "loc": "Mahalaxmi",
  "status": "Under construction",
  "bud": "b3,b4",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1771514885/gallery/48e3dfc3-a777-4cdd-b855-f4a17bad523c.webp",
  "phClass": null,
  "dev": "K Raheja Corp",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹12.52 Cr",
  "name": "Raheja Modern Vivarea",
  "locText": "Mahalaxmi",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "shapoorji_minerva",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767730739/gallery/99fcb223-ff4b-42c4-9591-e66a5ccdaa4d.webp",
  "loc": "Mahalaxmi",
  "status": "Ready to move",
  "bud": "b3,b4",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767730739/gallery/99fcb223-ff4b-42c4-9591-e66a5ccdaa4d.webp",
  "phClass": null,
  "dev": "Shapoorji Pallonji",
  "badge": null,
  "statusLabel": "Ready to move",
  "npLoc": null,
  "price2": "₹10 Cr",
  "name": "Shapoorji Minerva",
  "locText": "Mahalaxmi",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": true,
  "prop": null,
  "img": null,
  "loc": "Prabhadevi",
  "status": "",
  "bud": "",
  "phUrl": null,
  "phClass": null,
  "dev": null,
  "badge": null,
  "statusLabel": null,
  "npLoc": "Prabhadevi",
  "price2": null,
  "name": "25 South",
  "locText": "Prabhadevi",
  "meta": null,
  "vw": "Enquire →"
 },
 {
  "np": false,
  "prop": "rustomjee_crown",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767121586/gallery/cc23d769-c4ec-4deb-8e2c-36dc0cde0c64.webp",
  "loc": "Prabhadevi",
  "status": "Ready to move",
  "bud": "b2,b3",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1767121586/gallery/cc23d769-c4ec-4deb-8e2c-36dc0cde0c64.webp",
  "phClass": null,
  "dev": "Rustomjee",
  "badge": null,
  "statusLabel": "Ready to move",
  "npLoc": null,
  "price2": "From ₹9.75 Cr",
  "name": "Rustomjee Crown",
  "locText": "Prabhadevi",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "rustomjee_180_bay_view",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770405979/gallery/95f53267-ba4f-44c8-916b-a53c92e38ad7.webp",
  "loc": "Matunga",
  "status": "Under construction",
  "bud": "b1,b2",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1770405979/gallery/95f53267-ba4f-44c8-916b-a53c92e38ad7.webp",
  "phClass": null,
  "dev": "Rustomjee",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹4.12 Cr",
  "name": "Rustomjee 180 Bay View",
  "locText": "Matunga",
  "meta": null,
  "vw": "View details →"
 },
 {
  "np": false,
  "prop": "lt_island_cove",
  "img": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766663940/gallery/b7c98561-d06f-42b3-a47e-acc5b067516b.png",
  "loc": "Mahim",
  "status": "Under construction",
  "bud": "b1,b2",
  "phUrl": "https://res.cloudinary.com/dunx06tqm/image/upload/w_1300,q_auto,f_auto/v1766663940/gallery/b7c98561-d06f-42b3-a47e-acc5b067516b.png",
  "phClass": null,
  "dev": "L&T",
  "badge": null,
  "statusLabel": "Under construction",
  "npLoc": null,
  "price2": "From ₹3.25 Cr",
  "name": "L&T Island Cove",
  "locText": "Mahim",
  "meta": null,
  "vw": "View details →"
 }
];

export const MARQUEE = [
 {
  "prop": "aureus",
  "img": "aureus_entrance",
  "bgClass": "bg-aureus_entrance",
  "nm": "Lodha Aureus",
  "lo": "Sewri"
 },
 {
  "prop": "sobha",
  "img": "sobha_dusk",
  "bgClass": "bg-sobha_dusk",
  "nm": "Sobha Inizio",
  "lo": "Parel"
 },
 {
  "prop": "divino",
  "img": "divino_greens",
  "bgClass": "bg-divino_greens",
  "nm": "Lodha Divino",
  "lo": "Matunga"
 },
 {
  "prop": "icc",
  "img": "icc",
  "bgClass": "bg-icc",
  "nm": "Three ICC",
  "lo": "Dadar"
 },
 {
  "prop": "aureus",
  "img": "aureus_living",
  "bgClass": "bg-aureus_living",
  "nm": "Lodha Aureus",
  "lo": "Interiors"
 },
 {
  "prop": "sobha",
  "img": "sobha_lobby",
  "bgClass": "bg-sobha_lobby",
  "nm": "Sobha Inizio",
  "lo": "The Lobby"
 },
 {
  "prop": "divino",
  "img": "divino_pool",
  "bgClass": "bg-divino_pool",
  "nm": "Lodha Divino",
  "lo": "The Clubhouse"
 },
 {
  "prop": "sobha",
  "img": "sobha_ext",
  "bgClass": "bg-sobha_ext",
  "nm": "Sobha Inizio",
  "lo": "The Tower"
 }
];

export const DEV_LOGOS = [
 {
  "src": "/img/img-22.png",
  "w": "101",
  "h": "132",
  "alt": "K Raheja Corp"
 },
 {
  "src": "/img/img-23.png",
  "w": "286",
  "h": "132",
  "alt": "Oberoi Realty"
 },
 {
  "src": "/img/img-24.png",
  "w": "580",
  "h": "114",
  "alt": "Kalpataru"
 },
 {
  "src": "/img/img-25.png",
  "w": "276",
  "h": "132",
  "alt": "Birla Estates"
 },
 {
  "src": "/img/img-26.png",
  "w": "580",
  "h": "91",
  "alt": "Lodha"
 },
 {
  "src": "/img/img-27.png",
  "w": "580",
  "h": "120",
  "alt": "Sobha"
 },
 {
  "src": "/img/img-28.png",
  "w": "405",
  "h": "132",
  "alt": "L&T Realty"
 },
 {
  "src": "/img/img-29.png",
  "w": "580",
  "h": "79",
  "alt": "Bombay Dyeing"
 },
 {
  "src": "/img/img-30.png",
  "w": "580",
  "h": "104",
  "alt": "Shapoorji Pallonji"
 },
 {
  "src": "/img/img-31.png",
  "w": "500",
  "h": "132",
  "alt": "Raheja Universal"
 },
 {
  "src": "/img/img-32.png",
  "w": "145",
  "h": "132",
  "alt": "Hiranandani"
 },
 {
  "src": "/img/img-33.png",
  "w": "580",
  "h": "99",
  "alt": "Tribeca"
 },
 {
  "src": "/img/img-34.png",
  "w": "580",
  "h": "101",
  "alt": "Avighna"
 },
 {
  "src": "/img/img-35.png",
  "w": "385",
  "h": "132",
  "alt": "Adani"
 }
];

export const REVIEWS = [
  { q: "He told me what was wrong with three flats before what was right. No broker had ever done that. We closed on the fourth and I trust the decision completely.", img: "/img/img-36.jpg", nm: "Karan Shah", lo: "South Mumbai" },
  { q: "As an NRI I was nervous buying from abroad. Nikhil sent video from the exact floor, kept everything in writing, and answered every message the same day.", img: "/img/img-37.jpg", nm: "Nikita Jain", lo: "Bandra West" },
  { q: "I thought using an advisor would cost me more. It was the opposite. He negotiated hard on my side and saved me a genuine amount on the final number.", img: "/img/img-38.jpg", nm: "Aditya Rao", lo: "Worli" },
  { q: "No spam, no twenty site visits. He brought me three homes that actually fit what I asked for, and one of them was exactly right.", img: "/img/img-39.jpg", nm: "Sneha Kulkarni", lo: "Powai" },
  { q: "The finance background shows. He walked me through the real numbers, the true comparables and the paperwork, calmly, at every step.", img: "/img/img-40.jpg", nm: "Vivek Malhotra", lo: "Lower Parel" },
  { q: "He stayed with us through possession, not only till the token. That is rare. I have already introduced him to two friends.", img: "/img/img-41.jpg", nm: "Anjali Desai", lo: "Prabhadevi" },
];

export const FAQS = [
  ["Do I pay you extra for this?", "No. You will not pay more for having me represent you. My work is to bring the price down in your favour and protect you on the paperwork, not to add a cost on top."],
  ["How are you different from a broker?", "A broker usually works for the builder. I work for you. I show you only what fits your brief, I tell you the flaws before the features, and I negotiate on your side of the table."],
  ["Will you flood me with calls?", "No. This is a private advisory, not a call centre. One relationship, handled personally. Your details never go into a lead pool."],
  ["I have been let down before.", "Then you already understand why buyer-side representation exists. Everything with me is in writing, and I stay with you through possession, not only until the token is paid."],
  ["I am an NRI buying from abroad.", "I act as your eyes on the ground. Video from the actual floor you are buying, verified RERA and title checks, and everything on record before any money moves."],
  ["Do you handle commercial as well?", "Yes. Alongside luxury residential, I advise on select commercial mandates across Mumbai for the same clients."],
];

export const STEPS = [
  ["01", "A private consultation", "We talk. You tell me the home you want and the things you will not compromise on. No forms in a pile, no call centre."],
  ["02", "A curated shortlist", "I bring a handful of residences that genuinely fit your brief. No mass listings, no twenty-site weekends."],
  ["03", "An honest read on each", "I tell you what is wrong with a home before what is right. The view, the layout, the builder, the paperwork, the price."],
  ["04", "Negotiated on your side", "One visit that counts, then I hold the line on price and documentation, and stay with you through possession and beyond."],
];

export const LEDGER = [
  ["Shows you what pays him the most", "Shows you what fits your brief"],
  ["Hides the flaws until after you sign", "Tells you the flaws first, on every home"],
  ["Uses your budget against you", "Negotiates the price in your favour"],
  ["Disappears once the token is paid", "Stays through possession and beyond"],
];

// Areas used across the sell + consultation forms
export const AREAS = ["Wadala","Sion","Dadar","Parel","Sewri","Mahalaxmi","Worli","Lower Parel","Prabhadevi","Bandra","Other"];
export const CONTACT = { whatsapp: "919167243606", waDisplay: "+91 91672 43606", tel: "+919167243606", tidycal: "https://tidycal.com/nbrealtorr/30-minute-meeting" };
